/* Generated by           cobc 3.3-dev.0 */
/* Generated from         prog2.cob */
/* Generated at           Jul 15 2026 16:51:09 */
/* GnuCOBOL build date    Jul 05 2026 21:52:41 */
/* GnuCOBOL package date  Jun 15 2026 14:48:00 UTC */
/* Compile command        cobc -g -Wall prog2.cob */

/* Program local variables for 'A' */

/* Module initialization indicator */
static unsigned int	A_initialized = 0;

/* Module structure pointer for recursive */
static cob_module		*A_module = NULL;

/* Global variable pointer */
static cob_global		*A_cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */
static unsigned char	*b_17 = NULL;  /* VAR-IN */
unsigned char	*b_18 = NULL;  /* VAR-OUT */

/* Parent class(es) */
const char* A_parent_classes[] = {"B"};

/* Method names */
const char* A_method_names[] = {"A_method"};


/* Call parameters */
cob_field		**cob_procedure_params;

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	*frame_stack;


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_99[2] __attribute__((aligned));	/* a-var */

/* End of local data storage */


/* Fields for recursive routine */
static cob_field f_18	= {2, b_99, &a_2};	/* VAR-OUT */

/* End of fields */

