/* Generated by           cobc 3.3-dev.0 */
/* Generated from         prog2.cob */
/* Generated at           Jul 15 2026 16:51:09 */
/* GnuCOBOL build date    Jul 05 2026 21:52:41 */
/* GnuCOBOL package date  Jun 15 2026 14:48:00 UTC */
/* Compile command        cobc -g -Wall prog2.cob */

/* Program local variables for 'B' */

/* Module initialization indicator */
static unsigned int	B_initialized = 0;

/* Module structure pointer for recursive */
static cob_module		*B_module = NULL;

/* Global variable pointer */
static cob_global		*B_cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */
static unsigned char	*b_17 = NULL;  /* VAR-IN */
unsigned char	*b_18 = NULL;  /* VAR-OUT */

/* Parent class(es) */
const int B_parent_class_count = 0;
const char* B_parent_classes[] = {};

/* Method names */
const char* B_method_names[] = {"B_method"};


/* Call parameters */
cob_field		**cob_procedure_params;

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	*frame_stack;


/* Data storage */
static int	b_2;	/* RETURN-CODE */

/* End of local data storage */


/* Fields for recursive routine */
static cob_field f_18	= {2, NULL, &a_2};	/* VAR-OUT */

/* End of fields */

