/* Generated by           cobc 3.3-dev.0 */
/* Generated from         func.cob */
/* Generated at           Sep 08 2026 17:20:14 */
/* GnuCOBOL build date    Sep 04 2026 17:51:42 */
/* GnuCOBOL package date  Sep 04 2026 12:21:37 UTC */
/* Compile command        cobc -g func.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"func.cob"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 08 2026 17:20:14"
#define  COB_MODULE_DATE		20260908
#define  COB_MODULE_TIME		172014

/* Global variables */
#include "func.c.h"

/* Function prototypes */

cob_field		*MYMETHOD (cob_field **, const int);
static cob_field	*MYMETHOD_ (const int);
static void		MYMETHOD_module_init (cob_module *module);
COB_EXT_EXPORT int		prog (void);
static int		prog_ (const int);
static void		prog_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* FUNCTION-ID 'MyMethod' */

/* ENTRY 'MYMETHOD' */

cob_field *
MYMETHOD (cob_field **cob_fret, const int cob_pam)
{
  struct cob_func_loc	*floc;

  /* Save environment */
  floc = cob_save_func (cob_fret, cob_pam, 0);
  cob_call_params = cob_get_global_ptr ()->cob_call_params;
  floc->ret_fld = MYMETHOD_ (0);
  **cob_fret = *floc->ret_fld;

  /* Restore environment */
  cob_restore_func (floc);
  return *cob_fret;
}

static cob_field *
MYMETHOD_ (const int entry)
{
  /* Program local variables */
  #include "func.c.l1.h"

  /* Start of function code */

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return NULL;

  MYMETHOD_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Set address of module parameter list */
  cob_procedure_params = cob_malloc (1U * sizeof(void *));
  module->cob_procedure_params = cob_procedure_params;

  /* Set recursive frame stack pointer */
  frame_stack = cob_malloc (63U * sizeof(struct cob_frame));
  frame_ptr = frame_stack;
  frame_overflow = frame_ptr + 63 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module reference count */
  cob_reference_count++;

  /* Storage for returning item */
  b_18 = cob_malloc (2U);

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 7         : Entry     MyMethod                : func.cob */
  l_2:;
#line 7 "func.cob"
  ENTRY_MYMETHOD:	cob_nop ();
#line 121 "func.c"

  /* Line: 7         : MOVE               : func.cob */
#line 7 "func.cob"
  cob_nop ();
#line 126 "func.c"
  memmove (b_18, b_17, 2);

  /* Line: 8         : DISPLAY            : func.cob */
#line 8 "func.cob"
  cob_nop ();
#line 132 "func.c"
  cob_display (0, 1, 1, &c_1);

  /* Function exit */

  exit_function:

  /* Decrement module reference count */
  if (cob_reference_count) {
  	cob_reference_count--;
  }

  /* Free frame stack / call parameters */
  cob_free (frame_stack);
  cob_free (cob_procedure_params);

  /* Pop module stack */
  cob_module_leave (module);

  /* Free for recursive module */
  cob_module_free (&module);

  /* Function return */
  return COB_SET_DATA (f_18, b_18);
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  {
    const int temp_idx = 0;
    memcpy ((cob_u8_t *)&b_2, &temp_idx, sizeof(temp_idx));
  }


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;

}

/* End FUNCTION-ID 'MyMethod' */

/* Initialize module structure for MyMethod */
static void MYMETHOD_module_init (cob_module *module__)
{
  module__->module_name = "MyMethod";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_entry.funcptr = (void *(*)())MYMETHOD;
  module__->module_cancel.funcptr = NULL;
  module__->module_ref_count = &cob_reference_count;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 1;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

/* PROGRAM-ID 'prog' */

/* ENTRY 'prog' */

int
prog ()
{
  return prog_ (0);
}

static int
prog_ (const int entry)
{
  /* Program local variables */
  #include "func.c.l2.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Increment module reference count */
  cob_reference_count++;

  /* Entry dispatch */
  goto l_5;

  /* PROCEDURE DIVISION */

  /* Line: 21        : Entry     prog                    : func.cob */
  l_5:;
#line 21 "func.cob"
  ENTRY_PROG:	cob_nop ();
#line 280 "func.c"

  /* Line: 21        : DISPLAY            : func.cob */
#line 21 "func.cob"
  cob_nop ();
#line 285 "func.c"
  cob_display (0, 1, 1, func_MYMETHOD.funcfld (&cob_dyn_0, 1, (cob_field *)&c_2));

  /* Line: 22        : SET                : func.cob */
#line 22 "func.cob"
  cob_nop ();
#line 291 "func.c"
  memcpy (b_36, "28", 2);

  /* Line: 23        : DISPLAY            : func.cob */
#line 23 "func.cob"
  cob_nop ();
#line 297 "func.c"
  cob_display (0, 1, 1, &f_36);

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Decrement module reference count */
  if (cob_reference_count) {
  	cob_reference_count--;
  }

  /* Deallocate dynamic FUNCTION-ID fields */
  if (cob_dyn_0) {
    if (cob_dyn_0->data) {
      cob_free (cob_dyn_0->data);
    }
    cob_free (cob_dyn_0);
    cob_dyn_0 = NULL;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_21;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  func_MYMETHOD.funcvoid = cob_resolve_func ("MYMETHOD");
  prog_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
#line 11 "register-definition"
  cob_nop ();
#line 360 "func.c"
  {
    const int temp_idx = 0;
    memcpy ((cob_u8_t *)&b_21, &temp_idx, sizeof(temp_idx));
  }

  /* initialize field a-var */
#line 18 "func.cob"
  cob_nop ();
#line 369 "func.c"
  memset (b_36, (unsigned char)'0', 2);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  func_MYMETHOD.funcvoid = NULL;
  b_21 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'prog' */

/* Initialize module structure for prog */
static void prog_module_init (cob_module *module__)
{
  module__->module_name = "prog";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_entry.funcptr = (void *(*)())prog;
  module__->module_cancel.funcptr = (void *(*)())prog_;
  module__->module_ref_count = &cob_reference_count;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 0;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

/* End functions */

