/* Generated by           cobc 3.3-dev.0 */
/* Generated from         prog2.cob */
/* Generated at           Jul 15 2026 16:51:09 */
/* GnuCOBOL build date    Jul 05 2026 21:52:41 */
/* GnuCOBOL package date  Jun 15 2026 14:48:00 UTC */
/* Compile command        cobc -g -Wall prog2.cob */

#include <stdio.h>
#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"prog2.cob"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Jul 15 2026 16:51:09"
#define  COB_MODULE_DATE		20260715
#define  COB_MODULE_TIME		165109

/* Global variables */
#include "prog.c.h"

/* Function prototypes */

void	A_ (struct cob_factory_obj*);
void	B_ (struct cob_factory_obj*);

COB_EXT_EXPORT int		prog (void);
static int		prog_ (const int);
static void		prog_module_init (cob_module *module);
static void		A_module_init (cob_module *module);
static void		B_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* CLASS-ID 'MyClass' */

/* ENTRY 'MYCLASS' */

/* Should return a cob_factory object */
// cob_factory_obj*
// MYCLASS (void)
// {
//   struct cob_func_loc	*floc;

//   /* Save environment */
//   // floc = cob_save_func (cob_fret, cob_pam, 0);
//   cob_call_params = cob_get_global_ptr ()->cob_call_params;
//   floc->ret_fld = MYCLASS_ (0);
//   // **cob_fret = *floc->ret_fld;

//   /* Restore environment */
//   cob_restore_func (floc);
//   /* return reference to a class object below */
//   return NULL;
// }



void
A_ (struct cob_factory_obj* class_obj)
{
  /* Class static variables */
  #include "A.c.l1.h"

  #define module A_module
  #define initialized A_initialized
  #define cob_glob_ptr A_cob_glob_ptr

  struct cob_parent_class_list* parent_class_list;

  /* Start of function code */

  /* Check initialized, check module allocated, */ 
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, 0, 0))
  	return;

  A_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Set address of module parameter list */
  cob_procedure_params = cob_malloc (1U * sizeof(void *));
  module->cob_procedure_params = cob_procedure_params;

  /* Set recursive frame stack pointer */
  frame_stack = cob_malloc (63U * sizeof(struct cob_frame));
  frame_ptr = frame_stack;
  frame_overflow = frame_ptr + 63 - 1;

  /* Initialize rest of program */
  printf("A Initialized: %d\n", initialized);
  if (unlikely(A_initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:
    printf ("Initializing Class A ... Done\n");

  /* Increment module reference count */
  cob_reference_count++;

  /* Storage for returning item */
  b_18 = cob_malloc (2U);

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 7         : Entry     Static class initializer (factory procedure division?) -- MyClassInitializer                : prog2.cob */
  l_2:;
  ENTRY_MYCLASS:	cob_nop ();

  /* Function exit */

  exit_function:

  /* Decrement module reference count */
  
  // CHECKME: The module should still stay loaded when the initializer terminates.
  if (cob_reference_count) {
  	cob_reference_count--;
  }

  /* Free frame stack / call parameters */
  cob_free (frame_stack);
  cob_free (cob_procedure_params);

  /* Pop module stack */
  cob_module_leave (module);

  /* Free for recursive module */
  cob_module_free (&module);

  /* Function return */
  return;
  P_cgerror:
    printf("161\n");
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Class initialization */
  P_initialize:
      printf ("Initializing Class A\n");
      printf ("Initializing parent classes of A\n");
      class_obj->class_name = "A";

      if ((sizeof(A_parent_classes) / sizeof(char*)) > 0) {
        parent_class_list = (struct cob_parent_class_list*) cob_malloc (
                              sizeof(struct cob_parent_class_list));
        parent_class_list->next = NULL;
  
        for (int i = 0; i < sizeof(A_parent_classes)/sizeof(char*); i++) {
          printf ("Inherited class: %s\n", A_parent_classes[i]);
          parent_class_list->parent_class = cob_load_class (A_parent_classes[i]);
  
          class_obj->parent_classes = parent_class_list;
        }
      }

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  {
    const int temp_idx = 0;
    memcpy ((cob_u8_t *)&b_2, &temp_idx, sizeof(temp_idx));
  }


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return;

  #undef initialized
  #undef module
  #undef cob_glob_ptr

}

void
B_ (struct cob_factory_obj* class_obj)
{
  /* Class static variables */
  #include "B.c.l1.h"

  #define module B_module
  #define initialized B_initialized
  #define cob_glob_ptr B_cob_glob_ptr

  struct cob_parent_class_list* parent_class_list;

  /* Start of function code */

  /* Check initialized, check module allocated, */ 
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, 0, 0))
  	return;

  B_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Set address of module parameter list */
  cob_procedure_params = cob_malloc (1U * sizeof(void *));
  module->cob_procedure_params = cob_procedure_params;

  /* Set recursive frame stack pointer */
  frame_stack = cob_malloc (63U * sizeof(struct cob_frame));
  frame_ptr = frame_stack;
  frame_overflow = frame_ptr + 63 - 1;

  /* Initialize rest of program */
  printf("B Initialized: %d\n", initialized);
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:
    printf ("Initializing Class B ... Done\n");

  /* Increment module reference count */
  cob_reference_count++;

  /* Storage for returning item */
  b_18 = cob_malloc (2U);

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 7         : Entry     Static class initializer (factory procedure division?) -- MyClassInitializer                : prog2.cob */
  l_2:;
  ENTRY_MYCLASS:	cob_nop ();

  /* Function exit */

  exit_function:

  /* Decrement module reference count */
  
  // CHECKME: The module should still stay loaded when the initializer terminates.
  if (cob_reference_count) {
  	cob_reference_count--;
  }

  /* Free frame stack / call parameters */
  cob_free (frame_stack);
  cob_free (cob_procedure_params);

  /* Pop module stack */
  cob_module_leave (module);

  /* Free for recursive module */
  cob_module_free (&module);


  /* Function return */
  return;
  P_cgerror:
    printf("161\n");
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Class initialization */
  P_initialize:
      printf ("Initializing Class B\n");
      printf ("Initializing parent classes of B\n");
      class_obj->class_name = "B";

      /* Fill parent_classes only if a parent exists */
      if ((sizeof(B_parent_classes) / sizeof(char*)) > 0) {
        parent_class_list = (struct cob_parent_class_list*) cob_malloc (
                              sizeof(struct cob_parent_class_list));
        parent_class_list->next = NULL;
  
        for (int i = 0; i < sizeof(B_parent_classes) / sizeof(char*); i++) {
          printf ("Inherited class: %s\n", B_parent_classes[i]);
          parent_class_list->parent_class = cob_load_class (B_parent_classes[i]);
  
          class_obj->parent_classes = parent_class_list;
        }
      }


  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  {
    const int temp_idx = 0;
    memcpy ((cob_u8_t *)&b_2, &temp_idx, sizeof(temp_idx));
  }


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return;

  #undef initialized
  #undef module
  #undef cob_glob_ptr
}


/* Initialize module structure for A */
static void A_module_init (cob_module *module__)
{
  module__->module_name = "A";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_cancel.funcptr = NULL;
  module__->module_ref_count = &cob_reference_count;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 1;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

/* Initialize module structure for B */
static void B_module_init (cob_module *module__)
{
  module__->module_name = "B";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_cancel.funcptr = NULL;
  module__->module_ref_count = &cob_reference_count;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 1;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

/* PROGRAM-ID 'prog' */

/* ENTRY 'prog' */

int
prog ()
{
  return prog_ (0);
}

static int
prog_ (const int entry)
{
  printf("Inside prog_\n");
  /* Program local variables */
  #include "prog.c.l2.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0)) {
  	return -1;
  }

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:
    printf("\nP_ret_initialize\n");

  /* Increment module active */
  module->module_active++;

  /* Increment module reference count */
  cob_reference_count++;

  /* Entry dispatch */
  goto l_5;

  /* PROCEDURE DIVISION */

  /* Line: 21        : Entry     prog                    : prog2.cob */
  l_5:;
  ENTRY_PROG:	cob_nop ();

  /* Line: 21        : DISPLAY            : prog2.cob */
  cob_nop ();
  /* Function call executed normally after the funcptr has been set */
  // cob_display (0, 1, 1, func_MYMETHOD.funcfld (&cob_dyn_0, 1, (cob_field *)&c_2));

  /* Line: 22        : DISPLAY            : prog2.cob */
  cob_nop ();
  // cob_display (0, 1, 1, func_MYMETHOD.funcfld (&cob_dyn_1, 1, (cob_field *)&c_3));

  /* Line: 23        : MOVE               : prog2.cob */
  cob_nop ();
  memcpy (b_36, "98", 2);

  /* Line: 24        : DISPLAY            : prog2.cob */
  cob_nop ();
  // cob_display (0, 1, 1, func_MYMETHOD.funcfld (&cob_dyn_2, 1, &f_36));

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Decrement module reference count */
  if (cob_reference_count) {
  	cob_reference_count--;
  }

  /* Deallocate dynamic FUNCTION-ID fields */
  if (cob_dyn_0) {
    if (cob_dyn_0->data) {
      cob_free (cob_dyn_0->data);
    }
    cob_free (cob_dyn_0);
    cob_dyn_0 = NULL;
  }
  if (cob_dyn_1) {
    if (cob_dyn_1->data) {
      cob_free (cob_dyn_1->data);
    }
    cob_free (cob_dyn_1);
    cob_dyn_1 = NULL;
  }
  if (cob_dyn_2) {
    if (cob_dyn_2->data) {
      cob_free (cob_dyn_2->data);
    }
    cob_free (cob_dyn_2);
    cob_dyn_2 = NULL;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_21;
  P_cgerror:
    printf("364\n");
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:
    printf("Initializing program...\n");

  prog_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* call initializer (cob_load_class) API */
  printf ("cob_load_class called for A\n");
  obj_A = cob_load_class ("A");

  printf ("\nobj_A->class_name: %s\n", obj_A->class_name);
  printf ("obj_A->parent_classes->parent_class->class_name: %s\n",
         obj_A->parent_classes->parent_class->class_name);

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  cob_nop ();
  {
    const int temp_idx = 0;
    memcpy ((cob_u8_t *)&b_21, &temp_idx, sizeof(temp_idx));
  }

  /* initialize field a-var */
  cob_nop ();
  memset (b_36, (unsigned char)'0', 2);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active) {
    printf("430\n");
  	cob_fatal_error (COB_FERROR_CANCEL);
  }
    
  // func_MYMETHOD.funcvoid = NULL;
  b_21 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  printf ("DONE\n");
  return 0;

}

/* End PROGRAM-ID 'prog' */

/* Initialize module structure for prog */
static void prog_module_init (cob_module *module__)
{
  module__->module_name = "prog";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_entry.funcptr = (void *(*)())prog;
  module__->module_cancel.funcptr = (void *(*)())prog_;
  module__->module_ref_count = &cob_reference_count;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 0;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

/* End functions */


int main (int argc, char **argv)
{
  printf ("START\n");
  cob_init (argc, argv);
  cob_stop_run (prog ());
}