/* Generated by           cobc 3.3-dev.0 */
/* Generated from         prog2.cob */
/* Generated at           Jul 15 2026 16:51:09 */
/* GnuCOBOL build date    Jul 05 2026 21:52:41 */
/* GnuCOBOL package date  Jun 15 2026 14:48:00 UTC */
/* Compile command        cobc -g -Wall prog2.cob */

#include "libcob/common.h"
#include <assert.h>
#include <stdio.h>
#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"prog2.cob"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Jul 15 2026 16:51:09"
#define  COB_MODULE_DATE		20260715
#define  COB_MODULE_TIME		165109

/* Global variables */
#include "prog.c.h"

/* Function prototypes */

COB_EXT_EXPORT int	_ZN6ClassAE (const int);
COB_EXT_EXPORT int	_ZN6ClassBE (const int);

COB_EXT_EXPORT int		prog (void);
static int		prog_ (const int);

static void   A_module_init (cob_module *module__);
static void   B_module_init (cob_module *module__);
static void		prog_module_init (cob_module *module);

/* Functions */

cob_field * SayHelloFromClassA (cob_field **cob_fret, const int cob_pam);
static cob_field * SayHelloFromClassA_ (const int entry);

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}


COB_EXT_EXPORT int
_ZN6ClassAE (const int entry)
{
/* Class static variables */
#include "A.c.l1.h"
  // class_obj->module_init = &A_module_init;

  printf("Initializing Class A\n");
  printf("Initializing parent classes of A\n");

  /* Entry dispatch */
  switch (entry) {
  case 0:
	  goto l_factory_data_initializer;
  case 1:
	  goto l_instance_data_initializer;
  // 1:
	//   goto l_code_of_method1;
  // 2:
	//   goto l_code_of_method2;
  }

 l_factory_data_initializer:;
   /* Push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0)) {
      return -1;
  }

  A_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* module->oo_class_factory_obj =  */
  if (cob_init_factory_obj (module, "ClassA", A_parent_classes,
			    A_parent_class_count, A_methods, A_method_count,
			    /* size of instance data for A */10 /*Bytes*/)) {
	  /* error case: bail early */
	  return 1;
  }

  /* module->oo_class_factory_obj->class_fields_count = A_class_fields_count; */
  /* module->oo_class_factory_obj->class_fields = &A_class_fields[0]; */
  /* // module->oo_class_factory_obj->method_descriptors = method_names; */

  
  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  {
    const int temp_idx = 0;
    memcpy((cob_u8_t *)&b_2, &temp_idx, sizeof(temp_idx));
  }
  
  /* Pop module stack */
  /* TODO: Decide when the module is freed for classes. */
  cob_module_leave (module);

  return 0;

 l_instance_data_initializer:;
  /* Initialize WORKING-STORAGE for instance objects */
  {
  cob_u8_t object_data = cob_glob_ptr->cob_call_params[0];
    const int temp_idx = 0;
    memcpy((cob_u8_t *)&(data + <>), &temp_idx, sizeof(temp_idx));
  }

  return 0;
}

COB_EXT_EXPORT int
_ZN6ClassBE (const int entry)
{
/* Class static variables */
#include "B.c.l1.h"

  printf("Initializing Class B\n");
  printf("Initializing parent classes of B\n");

  /* Entry dispatch */
  switch (entry) {
  case 0:
	  goto l_factory_data_initializer;
  // 1:
	//   goto l_code_of_method1;
  // 2:
	//   goto l_code_of_method2;
  }

 l_factory_data_initializer:;
   /* Push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0)) {
      return -1;
  }

  B_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  module->oo_class_factory_obj = cob_init_factory_obj("ClassB", B_parent_classes,
    B_parent_class_count, B_methods, B_method_count);
  
  module->oo_class_factory_obj->class_fields_count = B_class_fields_count;
  module->oo_class_factory_obj->class_fields = &B_class_fields[0];
  // module->oo_class_factory_obj->method_descriptors = method_names;
  
  
  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  {
    const int temp_idx = 0;
    memcpy((cob_u8_t *)&b_2, &temp_idx, sizeof(temp_idx));
  }
  
  /* Pop module stack */
  /* TODO: Decide when the module is freed for classes. */
  cob_module_leave (module);

  return 0;
}


/* Initialize module structure for A */
static void 
A_module_init (cob_module *module__)
{
  module__->module_name = "A";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_cancel.funcptr = NULL;
  module__->module_ref_count = &cob_reference_count;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 1;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

/* Initialize module structure for B */
static void 
B_module_init (cob_module *module__)
{
  module__->module_name = "B";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_cancel.funcptr = NULL;
  module__->module_ref_count = &cob_reference_count;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 1;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

cob_field *
SayHelloFromClassA (cob_field **cob_fret, const int cob_pam)
{
  struct cob_func_loc	*floc;

  /* Save environment */
  floc = cob_save_func (cob_fret, cob_pam, 0);
  cob_call_params = cob_get_global_ptr ()->cob_call_params;
  floc->ret_fld = SayHelloFromClassA_ (0);
  **cob_fret = *floc->ret_fld;

  /* Restore environment */
  cob_restore_func (floc);
  return *cob_fret;
}

static cob_field *
SayHelloFromClassA_ (const int entry)
{
  /* Class A local variables */
  #include "A.c.l1.h"

  printf ("\nPrinting from function SayHelloFromClassA...\n");
  cob_display (0, 1, 1, &f_18);
  return COB_SET_DATA(f_18, b_18);
}

/* PROGRAM-ID 'prog' */

/* ENTRY 'prog' */

int
prog ()
{
  return prog_ (0);
}

static int
prog_ (const int entry)
{
  /* Program local variables */
  #include "prog.c.l2.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0)) {
  	return -1;
  }

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Increment module reference count */
  cob_reference_count++;

  /* Entry dispatch */
  goto l_5;

  /* PROCEDURE DIVISION */

  /* Line: 21        : Entry     prog                    : prog2.cob */
  l_5:;
  ENTRY_PROG:	cob_nop ();

  /* Line: 21        : DISPLAY            : prog2.cob */
  cob_nop ();
  /* currently using index positions like 0 */
  cob_display (0, 1, 1, obj_A_1->class_fields[0].class_field);

  /* Modify factory data */
  memcpy (obj_A_1->class_fields[0].class_field->data, "Hello, world!         ", 22);

  /* Print new factory data from obj_A_1 */
  cob_display (0, 1, 1, obj_A_1->class_fields[0].class_field);

  /* Print factory data from obj_A_2 */
  cob_display (0, 1, 1, obj_A_2->class_fields[0].class_field);

  // func_SayHelloFromA.funcvoid = cob_resolve_func("SayHelloFromClassA");
  // func_SayHelloFromA.funcnull(&cob_dyn_0, 1, NULL);

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Decrement module reference count */
  if (cob_reference_count) {
  	cob_reference_count--;
  }

  /* Deallocate dynamic FUNCTION-ID fields */
  if (cob_dyn_0) {
    if (cob_dyn_0->data) {
      cob_free (cob_dyn_0->data);
    }
    cob_free (cob_dyn_0);
    cob_dyn_0 = NULL;
  }
  if (cob_dyn_1) {
    if (cob_dyn_1->data) {
      cob_free (cob_dyn_1->data);
    }
    cob_free (cob_dyn_1);
    cob_dyn_1 = NULL;
  }
  if (cob_dyn_2) {
    if (cob_dyn_2->data) {
      cob_free (cob_dyn_2->data);
    }
    cob_free (cob_dyn_2);
    cob_dyn_2 = NULL;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_21;
  P_cgerror:
    printf("364\n");
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:
    printf("Initializing program...\n");

  prog_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* call initializer (cob_load_class) API */
  printf ("cob_load_class called for A\n");
  obj_A_1 = cob_load_class ("ClassA");
  obj_A_2 = cob_load_class ("ClassA");

  assert(obj_A_1 == obj_A_2);
  printf ("Same factory objects for class A...\n");

  printf ("\nobj_A->class_name: %s\n", obj_A_1->class_name);
  printf ("obj_A_1->parent_classes->class_name: %s\n",
         obj_A_1->parent_class_factory_objs->class_name);

  printf ("Methods for %s:\n", obj_A_1->class_name);
  for (int method_idx = 0; method_idx < obj_A_1->methods_count; ++method_idx) {
    printf ("  %s\n", obj_A_1->method_descriptors[method_idx].method_name);
  }

  

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  cob_nop ();
  {
    const int temp_idx = 0;
    memcpy ((cob_u8_t *)&b_21, &temp_idx, sizeof(temp_idx));
  }

  /* initialize field a-var */
  cob_nop ();
  memset (b_36, (unsigned char)'0', 2);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active) {
    printf("430\n");
  	cob_fatal_error (COB_FERROR_CANCEL);
  }
    
  // func_MYMETHOD.funcvoid = NULL;
  b_21 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  printf ("DONE\n");
  return 0;

}

/* End PROGRAM-ID 'prog' */

/* Initialize module structure for prog */
static void prog_module_init (cob_module *module__)
{
  module__->module_name = "prog";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_entry.funcptr = (void *(*)())prog;
  module__->module_cancel.funcptr = (void *(*)())prog_;
  module__->module_ref_count = &cob_reference_count;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 0;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

/* End functions */


int main (int argc, char **argv)
{
  printf ("START\n");
  cob_init (argc, argv);
  cob_stop_run (prog ());
}
