/* Generated by           cobc 3.3-dev.0 */
/* Generated from         prog2.cob */
/* Generated at           Jul 15 2026 16:51:09 */
/* GnuCOBOL build date    Jul 05 2026 21:52:41 */
/* GnuCOBOL package date  Jun 15 2026 14:48:00 UTC */
/* Compile command        cobc -g -Wall prog2.cob */

/* Program local variables for 'prog' */

struct cob_factory_obj* obj_A;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_28 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_29 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_30 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_31 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_32 = NULL;  /* XML-NTEXT */
static unsigned char	*b_33 = NULL;  /* XML-TEXT */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer for recursive */
static cob_module		*module = NULL;

/* Global variable pointer */
static cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	func_MYMETHOD;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Dynamic field FUNCTION-ID pointers */
cob_field	*cob_dyn_0 = NULL;
cob_field	*cob_dyn_1 = NULL;
cob_field	*cob_dyn_2 = NULL;

/* Data storage */
static int	b_21;	/* RETURN-CODE */
static cob_u8_t	b_36[2] __attribute__((aligned));	/* a-var */

/* End of local data storage */


/* Fields (local) */
static cob_field f_36	= {2, b_36, &a_2};	/* a-var */

/* End of fields */

